### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by zgornel** [JuliaNeighbors/HNSW.jl#17]
I believe the package is mature enough to be registered.

**Comment by JonasIsensee** [comment]
Hey, yes i suppose it is possible to register the package.
The idea of JuliaNeighbors hasn't really taken off though.
What's your opinion on that? Should we keep the "organization" or should I delete it and just register the package from my personal account?

**Comment by zgornel** [comment]
The ideea of the organization makes sense to me; the org needs a bit more packages and people.
 I should have added IVFADC.jl to it before registering...

**Comment by JonasIsensee** [comment]
https://github.com/JuliaRegistries/General/pull/4469

See here but also have a look at the comment.
HNSW is not a very telling name, I'm not a fan but I also don't know of any alternatives

**Comment by zgornel** [comment]
It actually is; not popular yet; thanknyou for registering!
